language: node_js
os:
  - linux
node_js:
  - "lts/*"
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn install
  - yarn lint
  - yarn type-check
  - yarn md-lint
  - if [ "$TRAVIS_BRANCH" = "release" ] && [ "$TRAVIS_EVENT_TYPE" = "push" ]; then travis_wait 120 yarn build; fi
after_success:
  - if [ "$TRAVIS_BRANCH" = "release" ] && [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then yarn lh -- --perf=70 --pwa=70 --seo=70 --bp=70 --a11y=70 https://staging.blog.rayriffy.com/; fi

before_deploy:
  - yarn global add netlify-cli

deploy:
  provider: script
  script: netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --prod --dir ./public
  skip_cleanup: true
  on:
    branch: release
