name: Test, Build & Deploy for Production

on:
  push:
    branches:
      - release

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: "Init: Use Node.js ${{ matrix.node-version }}"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Init: Install yarn"
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
        export PATH=$HOME/.yarn/bin:$PATH
    - name: "Init: Install dependencies"
      run: yarn
    - name: "Test: Type checking"
      run: yarn test:types
    - name: "Test: Code linting"
      run: yarn test:lint
    - name: "Test: Markdown linting"
      run: yarn test:markdown

  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: "Init: Use Node.js ${{ matrix.node-version }}"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Init: Install yarn"
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
        export PATH=$HOME/.yarn/bin:$PATH
    - name: "Init: Install dependencies"
      run: yarn
    - name: "Build: Trigger build staging site"
      run: yarn build
    - name: "Deploy: Upload to Netlify"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_PRODUCTION_SITE_ID: ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }}
      run: |
        yarn global add netlify-cli
        netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_PRODUCTION_SITE_ID --prod --dir ./public