name: Test, Build & Deploy for Production

on:
  push:
    branches:
      - release

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: "Init: Summon NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Artifacts: Upload node-modules-prod"
      uses: actions/upload-artifact@master
      with:
        name: node-modules-prod
        path: node_modules
    - name: "Init: Install dependencies"
      uses: borales/actions-yarn@master
      with:
        args: install
    - name: "Test: Type checking"
      uses: borales/actions-yarn@master
      with:
        args: test:types
    - name: "Test: Code linting"
      uses: borales/actions-yarn@master
      with:
        args: test:lint
    - name: "Test: Markdown linting"
      uses: borales/actions-yarn@master
      with:
        args: test:markdown
    - name: "Artifacts: Upload node-modules-prod"
      uses: actions/upload-artifact@master
      with:
        name: node-modules-prod
        path: node_modules

  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: "Init: Summon NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Init: Install dependencies"
      uses: borales/actions-yarn@master
      with:
        args: install
    - name: "Build: Trigger build staging site"
      uses: borales/actions-yarn@master
      env:
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      with:
        args: build
    - name: "Deploy: Upload to Netlify"
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }}
      with:
        args: deploy --dir=./public --prod
