name: Test, Build & Deploy for Staging

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: "Init: Summon NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Init: Install dependencies"
      uses: borales/actions-yarn@master
      with:
        args: install
    - name: "Test: Type checking"
      uses: borales/actions-yarn@master
      with:
        args: test:types
    - name: "Test: Code linting"
      uses: borales/actions-yarn@master
      with:
        args: test:lint
    - name: "Test: Markdown linting"
      uses: borales/actions-yarn@master
      with:
        args: test:markdown

  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: "Init: Summon NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Init: Install dependencies"
      uses: borales/actions-yarn@master
      with:
        args: install
    - name: "Build: Trigger build staging site"
      uses: borales/actions-yarn@master
      with:
        args: build:staging
    - name: "Deploy: Upload to Netlify"
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STAGING_SITE_ID }}
      with:
        args: deploy --dir=./public
